import Head from 'next/head'
import clientPromise from '../lib/mongodb'
import { InferGetServerSidePropsType } from 'next'
import Image from 'next/image'    
import styles from './Home.module.css'
import Navbar from './../components/navbar';
import Link  from 'next/link';

export async function getServerSideProps() {
  try {
    // `await clientPromise` will use the default database passed in the MONGODB_URI
    // However you can use another database (e.g. myDatabase) by replacing the `await clientPromise` with the following code:
    //
    const client = await clientPromise
    const db = client.db("ediary")

    //
    // Then you can execute queries against your database like so:
    // db.find({}) or any of the MongoDB Node Driver commands
    return {
      props: { isConnected: true },
    }
  } catch (e) {
    console.error(e)
    return {
      props: { isConnected: false },
    }
  }
}

export default function Home({
  isConnected,  
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  // console.log(isConnected)
  return (
    <div className={styles.home_container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar/>
    <main className={styles.head_main}>
      <h1>
        Welcome to E-Diary!
      </h1>
      <h2>Add Words To Your Memory </h2>
      <p>
        This is a simple diary app that allows you to write your daily thoughts, feelings and memories.
      </p>
      <button><Link href="/signup" >Create Account</Link></button>
    </main>
    <footer className={styles.head_footer}>
      this is the footer
    </footer>
  </div>
  )
}
